on: [push]

jobs:
  boman_scan:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          name: code-coverage-report
          path: output/code-coverage.json
      # Runs a single command using the runners shell
      - name: Install packages
        run: sudo pip install boman-cli
      - name: Run scan  
        run: sudo boman-cli -a run -u https://devapi.boman.ai/v2/
