on: [push]

jobs:
  boman_scan:
    runs-on: ubuntu-latest
    name: Boman
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Boman
        run: |
          sudo pip install --extra-index-url https://test.pypi.org/simple/ boman-cli-uat==0.8
          sudo boman-cli-uat -a run -u https://devapi.boman.ai/v2/
          
      - name: Upload boman result as raw file
        uses: actions/upload-artifact@v3
        with:
          name: boman_raw_files
          path: ./
